# Generated by Django 5.2.10 on 2026-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='trade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
